// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcTI6VtvEjfoXptpegOqeZgE9WbfKdamk',
    appId: '1:46856511092:web:437c665d9e4b2d0090bb21',
    messagingSenderId: '46856511092',
    projectId: 'ecotrack-58a29',
    authDomain: 'ecotrack-58a29.firebaseapp.com',
    databaseURL: 'https://ecotrack-58a29-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecotrack-58a29.firebasestorage.app',
    measurementId: 'G-HECQJQCDNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhDCcq95Gy7rSmT02fcCcmmtuZQBUs3Ec',
    appId: '1:46856511092:android:7d6d3dc796a7a4dc90bb21',
    messagingSenderId: '46856511092',
    projectId: 'ecotrack-58a29',
    databaseURL: 'https://ecotrack-58a29-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecotrack-58a29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc1jICot6gM5VNbD-KoDwNXv1O1zNj-z0',
    appId: '1:46856511092:ios:7d6b6feb020f7abf90bb21',
    messagingSenderId: '46856511092',
    projectId: 'ecotrack-58a29',
    databaseURL: 'https://ecotrack-58a29-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecotrack-58a29.firebasestorage.app',
    iosBundleId: 'com.example.ecotrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc1jICot6gM5VNbD-KoDwNXv1O1zNj-z0',
    appId: '1:46856511092:ios:7d6b6feb020f7abf90bb21',
    messagingSenderId: '46856511092',
    projectId: 'ecotrack-58a29',
    databaseURL: 'https://ecotrack-58a29-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecotrack-58a29.firebasestorage.app',
    iosBundleId: 'com.example.ecotrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcTI6VtvEjfoXptpegOqeZgE9WbfKdamk',
    appId: '1:46856511092:web:31747c00ad47451890bb21',
    messagingSenderId: '46856511092',
    projectId: 'ecotrack-58a29',
    authDomain: 'ecotrack-58a29.firebaseapp.com',
    databaseURL: 'https://ecotrack-58a29-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'ecotrack-58a29.firebasestorage.app',
    measurementId: 'G-CG67HP106W',
  );

}